# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build:
    services:
      docker-build:
        image: docker:dind
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
        MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

        # Use Docker in Docker with SSL (https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled)
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: /certs
        DOCKER_CERT_PATH: /certs/client
        DOCKER_TLS_VERIFY: 1
        DOCKER_DRIVER: overlay2
      run: mvn $MAVEN_CLI_OPTS clean deploy -Dit.postgresql.host=docker-build
      
